---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Supported on Debian >= 11
  ansible.builtin.fail:
    msg: Not supported on {{ ansible_distribution }} < 11
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version | int < 11

- name: Supported on Ubuntu >= 20
  ansible.builtin.fail:
    msg: Not supported on {{ ansible_distribution }} < 20
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int < 20

- name: Show support message
  ansible.builtin.fail:
    msg:
      - "Role 'firewalld' is not supported on {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  when: firewalld_unsupported is defined and not firewalld_unsupported

- name: Install firewalld
  ansible.builtin.include_tasks: install.yml
